In [17]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import hvplot.pandas

In [18]:
iris_df = pd.read_csv('new_iris.csv')
iris_df.head()

sepal_length  petal_length  sepal_width  petal_width
0           5.1           1.4          3.5          0.2
1           4.9           1.4          3.0          0.2
2           4.7           1.3          3.2          0.2
3           4.6           1.5          3.1          0.2
4           5.0           1.4          3.6          0.2

In [19]:
pca = PCA(n_components=2)

In [20]:
iris_scaled = StandardScaler().fit_transform(iris_df)
iris_scaled

array([[-9.00681170e-01, -1.34127240e+00,  1.03205722e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.34127240e+00, -1.24957601e-01,
        -1.31297673e+00],
       [-1.38535265e+00, -1.39813811e+00,  3.37848329e-01,
        -1.31297673e+00],
       [-1.50652052e+00, -1.28440670e+00,  1.06445364e-01,
        -1.31297673e+00],
       [-1.02184904e+00, -1.34127240e+00,  1.26346019e+00,
        -1.31297673e+00],
       [-5.37177559e-01, -1.17067529e+00,  1.95766909e+00,
        -1.05003079e+00],
       [-1.50652052e+00, -1.34127240e+00,  8.00654259e-01,
        -1.18150376e+00],
       [-1.02184904e+00, -1.28440670e+00,  8.00654259e-01,
        -1.31297673e+00],
       [-1.74885626e+00, -1.34127240e+00, -3.56360566e-01,
        -1.31297673e+00],
       [-1.14301691e+00, -1.28440670e+00,  1.06445364e-01,
        -1.44444970e+00],
       [-5.37177559e-01, -1.28440670e+00,  1.49486315e+00,
        -1.31297673e+00],
       [-1.26418478e+00, -1.22754100e+00,  8.00654259e-01,
      

In [22]:
iris_scaled_pca = pca.fit_transform(iris_scaled)
iris_scaled_pca

array([[-2.26454173e+00,  5.05703903e-01],
       [-2.08642550e+00, -6.55404729e-01],
       [-2.36795045e+00, -3.18477311e-01],
       [-2.30419716e+00, -5.75367713e-01],
       [-2.38877749e+00,  6.74767397e-01],
       [-2.07053681e+00,  1.51854856e+00],
       [-2.44571134e+00,  7.45626750e-02],
       [-2.23384186e+00,  2.47613932e-01],
       [-2.34195768e+00, -1.09514636e+00],
       [-2.18867576e+00, -4.48629048e-01],
       [-2.16348656e+00,  1.07059558e+00],
       [-2.32737775e+00,  1.58587455e-01],
       [-2.22408272e+00, -7.09118158e-01],
       [-2.63971626e+00, -9.38281982e-01],
       [-2.19229151e+00,  1.88997851e+00],
       [-2.25146521e+00,  2.72237108e+00],
       [-2.20275048e+00,  1.51375028e+00],
       [-2.19017916e+00,  5.14304308e-01],
       [-1.89407429e+00,  1.43111071e+00],
       [-2.33994907e+00,  1.15803343e+00],
       [-1.91455639e+00,  4.30465163e-01],
       [-2.20464540e+00,  9.52457317e-01],
       [-2.77416979e+00,  4.89517027e-01],
       [-1.

In [6]:
import plotly.figure_factory as ff

In [8]:
# Create the dendrogram
fig = ff.create_dendrogram(iris_scaled_pca, color_threshold=0)
fig.update_layout(width=800, height=500)
fig.show()

In [9]:
agg = AgglomerativeClustering(n_clusters=3)

In [10]:
model = agg.fit(iris_scaled_pca)

In [14]:
model.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2,
       2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1], dtype=int64)

In [15]:
iris_scaled_pca['class'] = model.labels_


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices